

version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: shopwise_postgres
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: airflow
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  airflow:
    image: apache/airflow:2.8.1-python3.9
    container_name: shopwise_airflow
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:airflow@postgres:5432/ecommerce
      AIRFLOW__CORE__FERNET_KEY: "SFfd8Fot7ANt02qS4uuSyVyyizdbC91A-xnJDYEuCF4="
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./sql:/opt/airflow/sql
      - ./data_lake:/opt/airflow/data_lake
      - ./logs:/opt/airflow/logs
      - ./.env:/opt/airflow/.env
      - ./dataset:/opt/airflow/dataset

    ports:
      - "8080:8080"
    working_dir: /opt/airflow
    command: bash -c "\
      while ! pg_isready -h postgres -U postgres; do sleep 1; done && \
      airflow db init && \
      airflow users create \
        --username admin21 --password admin2108 \
        --firstname Balaji --lastname Viswanathan \
        --role Admin --email admin21@localhost && \
      airflow webserver & airflow scheduler"

volumes:
  postgres_data:

