

services:
  postgres:
    image: postgres:13
    container_name: shopwise_postgres
    environment:
      POSTGRES_USER: project1_shopwise
      POSTGRES_PASSWORD: shopwise123!@
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  airflow-webserver:
    image: apache/airflow:2.9.1
    container_name: shopwise_airflow_web
    restart: always
    depends_on:
      - postgres
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://project1_shopwise:shopwise123!@@postgres/ecommerce

      AIRFLOW__CORE__LOAD_EXAMPLES: 'False'
    volumes:
      - ./dags:/opt/airflow/dags
      - ./scripts:/opt/airflow/scripts
      - ./data_lake:/opt/airflow/data_lake
      - ./sql:/opt/airflow/sql
      - ./.env:/opt/airflow/.env
    ports:
      - "8080:8080"
    command: >
      bash -c "airflow db init &&
               airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
               airflow webserver"

volumes:
  pg_data:
